version: "3.8"
services:
  backend:
    build:
      context: ../tp2-back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - VITE_API_URL=http://backend:3000
